# https://gohugo.io/getting-started/configuration/

baseURL              = "https://dshil.github.io/"
builddrafts          = false
canonifyurls         = true
contentdir           = "content"
languageCode         = "en-US"
layoutdir            = "layouts"
publishdir           = "public"
author               = "Dmitriy Shilin"
theme                = "cactus"
title                = "Dmitriy Shilin"
pluralizelisttitles  = false

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  blog  = "blog/:slug/"

[[menu.main]]
  name                 = "Home"
  weight               = 1
  url                  = "/"

[[menu.main]]
  name                 = "Blog"
  weight               = 2
  url                  = "/blog/"

[[menu.main]]
  name                 = "Talks"
  weight               = 3
  url                  = "/talks/"

[params]
  colortheme = "white"

  mainSection = "blog"
  description = "Various notes about Software Development"

  showProjectsList = true
  projectsUrl = "https://github.com/dshil"

  showAllPostsOnHomePage = false
  postsOnHomePage = 7

  copyright            = "Dmitriy Shilin"

  cachebuster          = true
  dateform             = "Jan 2, 2006"
  dateformfull         = "Mon Jan 2 2006 15:04:05 MST"
  lang                 = "en"

[[params.social]]
  name = "github"
  link = "https://github.com/dshil"

[[params.social]]
  name = "email"
  link = "dsh.public@fastmail.com"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/dmitriy-shilin-10032a8b"
