# https://gohugo.io/getting-started/configuration/

baseURL              = "https://dshil.github.io/"
builddrafts          = false
canonifyurls         = true
contentdir           = "content"
languageCode         = "en-US"
layoutdir            = "layouts"
publishdir           = "public"
author               = "Dmitriy Shilin"
theme                = "cactus"
title                = "Dmitriy Shilin"
disqusShortname      = "dshilblog"
googleAnalytics      = "UA-182319870-1"

[[menu.main]]
  name                 = "Home"
  weight               = 1
  url                  = "/"

[[menu.main]]
  name                 = "Blog"
  weight               = 2
  url                  = "/blog/"

[[menu.main]]
  name                 = "Talks"
  weight               = 3
  url                  = "/talks/"

[params]
  colortheme = "white"
  logo = "images/profile.png"
  icon = "images/icon.ico"

  mainSection = "blog"
  description = "Various notes about Software Development"

  showProjectsList = true
  projectsUrl = "https://github.com/dshil"

  showAllPostsOnHomePage = false
  postsOnHomePage = 6

  copyright            = "Dmitriy Shilin"

  tagsOverview = true

  cachebuster          = true
  dateFormat           = "Jan 2, 2006"
  lang                 = "en"

  googleAnalyticsAsync = true

  [params.comments]
    enabled = true
    engine = "disqus"

  [[params.social]]
    name = "github"
    link = "https://github.com/dshil"

  [[params.social]]
    name = "email"
    link = "dsh.public@fastmail.com"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/dmitriy-shilin-10032a8b"
