#!/usr/bin/env bash

msg="build site: `date`"

hugo -t cactus

pushd public
    git add -A

    if [ $# -eq 1 ]
      then msg="$1"
    fi

    git commit -m "$msg"
    git push origin master
popd # public
